version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Замініть це на фактичний MONGO_URL, або отримайте його з вашого .env
      # Цей файл .env не буде скопійовано в образ, але ви можете передати його значення
      # через змінну середовища.
      MONGO_URL: "mongodb+srv://saveoncarsfl:14tiZoRpdZ6NiW7N@cluster0.nr5jyaa.mongodb.net/datacar?retryWrites=true&w=majority"
    volumes:
      # Ця опція корисна для розробки. Вона монтує локальний код у контейнер.
      # Зміни у вашому коді на хості будуть відображатися всередині контейнера без перебудови образу.
      # Для продакшену зазвичай це не потрібно, достатньо `COPY . .` у Dockerfile.
      - .:/app
      - /app/node_modules # Важливо, щоб node_modules не перезаписалися локальним кодом
    restart: always # Автоматично перезапускати контейнер, якщо він виходить з ладу
